### ISSUE TITLE
Pickup Manager doesn't start properly

### ISSUE THREAD

**Issue by erandikag** [wso2-extensions/identity-samples-dotnet#3]
**Description:**
Followed the guide [1] and installed the pickup manager successfully. Started the PickupManager application and it shows following page.

![pickup_mgr_open_ui](https://user-images.githubusercontent.com/23738932/77245162-88623400-6c42-11ea-8c06-2875bc134546.PNG)

Note: I have entered all the information requested in the setup, inluding the Callback URL, but this UI again requested me to enter Callback URL although other entered values were populated properly.

I entered only the Callback URL (running the application as Administrator) and tried to proceed. It showed the same UI, with Callback URL filled.

Only after updating UserInfo, Logout, Callback, PostLogout in above UI, I was directed to below UI.

![pickup_mgr_ui](https://user-images.githubusercontent.com/23738932/77245563-6e762080-6c45-11ea-910f-7cd2d0abe77d.PNG)

When clicking the 'LOGIN' in above UI, application was closed after not responding for a while.

When 
[1] https://github.com/wso2-extensions/identity-samples-dotnet/releases/tag/v0.9.0

**Suggested Labels:**
Type/Bug, Severity/Blocker

**Affected Product Version:**
v0.9.0

**OS, DB, other environment details and versions:**    
OS: Windows 10 Enterprise

**Comment by janakamarasena** [comment]
I also experienced the same behaviour. When I clicked the Login button the app closed.

**Comment by erandikag** [comment]
(As per the fix: https://github.com/wso2-extensions/identity-sdks-dotnet/pull/2)
Configuring Callback URL as `http://localhost:8080/` worked with v0.9.0 release.
Note the trailing backslash.

**Comment by darshanasbg** [comment]
Updated the release note to,
* Enter all fields during the setup
* Have trailing backslash for the Callback URLs
