### ISSUE TITLE
Improvements for release note

### ISSUE THREAD

**Issue by erandikag** [wso2-extensions/identity-samples-dotnet#4]
**Description:**
[Release Note](https://github.com/wso2-extensions/identity-samples-dotnet/releases/tag/v0.9.0) improvement suggestions
1. Steps -> Setup WSO2 Identity Server, 4th point link should be https://is.docs.wso2.com/en/5.9.0/learn/configuring-users/, but currently it's https://is.docs.wso2.com/en/5.9.0/learn/configuring-roles-and-permissions/.

2. Add a step to 'Install Pickup-Manager Desktop Application' after 5th step, to populate the fields in 'Next' page of the installation. Otherwise, it keeps prompting for all those values when running the application as mentioned in #3.

3. It's better to have a link to setup in step 1 of 'Install Pickup-Manager Desktop Application'.

**Suggested Labels:**
Type/Improvement

**Comment by darshanasbg** [comment]
Updated release note fixing all 3 points.
