### ISSUE TITLE
Inconsistency among application authorization details labels

### ISSUE THREAD

**Issue by erandikag** [wso2-extensions/identity-samples-dotnet#6]
**Description:**
Authorization details field labels are inconsistent among setup and application UIs.
| Label in Installation Wizard | Label in Configuration UI in startup |
|-----------------|----------------------------------------|
| Authorization Endpoint | Authorize Endpoint | 
| Redirect URI | Callback URL |
| Postlogout Redirect URI | PostLogout | 

**Suggested Labels:**
Type/Improvement

**Comment by gayashanbc** [comment]
This issue is tracked from https://github.com/asgardio/asgardio-dotnet-oidc-sdk/issues/2
